name = "kotori316-maven-page"
compatibility_date = "2024-10-30"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "./dist"
send_metrics = false

[vars]
ENVIRONMENT = "staging"

[env.production.vars]
ENVIRONMENT = "production"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "MAVEN_BUCKET"
bucket_name = "kotori316-maven"

[[env.production.r2_buckets]]
binding = "MAVEN_BUCKET"
bucket_name = "kotori316-maven"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
