name = "kotori316-maven-worker"
compatibility_date = "2024-09-19"
# compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "./dist"
send_metrics = false

[assets]
directory = "./public/"
binding = "ASSETS"
experimental_serve_directly = true

[vars]
ENVIRONMENT = "production"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "MAVEN_BUCKET"
bucket_name = "kotori316-maven"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
