name: Check action
on:
  push:
    paths:
      - '.github/workflows/*.yaml'
      - '.github/workflows/*.yml'

jobs:
  check:
    # See https://github.com/Kotori316/common-script/blob/v2.0.3/.github/workflows/check-action.yaml
    uses: 'Kotori316/common-script/.github/workflows/check-action.yaml@f68c456ce9aa44130e67f05234bc68db848e9a54' # v2.0.5
    permissions:
      contents: read
