name: Copy Server Validation
on:
  push:
    paths:
      - 'reposilite-server-terraform/move_server/**'
      - '.github/workflows/copy-server.yaml'
    branches: main
  pull_request:
    paths:
      - 'reposilite-server-terraform/move_server/**'
      - '.github/workflows/copy-server.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: 'reposilite-server-terraform/move_server'
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t app .

  publish:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - test
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{secrets.GCP_IDENTITY_PROVIDER}}
          service_account: ${{secrets.GCP_SERVICE_ACCOUNT}}
      - uses: google-github-actions/setup-gcloud@v2
      - run: gcloud auth configure-docker us-central1-docker.pkg.dev
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Build Get
        uses: docker/build-push-action@v5
        id: build-action-get
        with:
          push: true
          tags: us-central1-docker.pkg.dev/kotori316-mods-resources/storage-copy-application/app:latest
          platforms: linux/amd64
          context: 'reposilite-server-terraform/move_server'
          file: 'reposilite-server-terraform/move_server/Dockerfile'
      - name: Deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: 'reposilite-server-copy-run'
          region: 'us-central1'
          image: 'us-central1-docker.pkg.dev/kotori316-mods-resources/storage-copy-application/app:latest'
          skip_default_labels: true
