name: "Delete snapshots"
on:
  schedule:
    - cron: "35 3 */7 * *"
  workflow_dispatch: {}

jobs:
  delete:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    container: 'node:20'
    defaults:
      run:
        working-directory: 'snapshot-delete'
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{secrets.GCP_IDENTITY_PROVIDER}}
          service_account: ${{secrets.GCP_SERVICE_ACCOUNT}}
      - name: Prepare log
        id: log
        run: |
          log_name="$(date "+%Y%m%d-%H%M%S")-delete-snapshot.json"
          echo "name=${log_name}" >> $GITHUB_OUTPUT
          echo "repo=$(basename "${{github.repository}}")" >> $GITHUB_OUTPUT
      - name: Get credentials
        id: get-secrets
        uses: google-github-actions/get-secretmanager-secrets@v2
        with:
          secrets: |-
            cloudflare_token:kotori316-mods-resources/cloudflare_token
            cloudflare_access_key:kotori316-mods-resources/cloudflare_access_key
            cloudflare_s3_endpoint:kotori316-mods-resources/cloudflare_s3_endpoint
            cloudflare_secret_key:kotori316-mods-resources/cloudflare_secret_key
      - name: Delete files
        run: npx tsx src/index.ts
        env:
          R2_ENDPOINT: ${{steps.get-secrets.outputs.cloudflare_s3_endpoint}}
          R2_ACCESS_KEY: ${{steps.get-secrets.outputs.cloudflare_access_key}}
          R2_SECRET_KEY: ${{steps.get-secrets.outputs.cloudflare_secret_key}}
          R2_BUCKET: 'kotori316-maven'
          RESULT_OUTPUT: '/tmp/${{steps.log.outputs.name}}'
          DRY_RUN: 'false'
      - name: Upload log
        if: ${{ !cancelled() }}
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: /tmp/${{steps.log.outputs.name}}
          destination: kotori316-logs/${{steps.log.outputs.repo}}
          process_gcloudignore: false
