on:
  push:
    paths:
      - reposilite-server-terraform/copy_job/*
      - .github/workflows/deploy-copy-task.yaml

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      metadata: ${{ steps.build-action-get.outputs.metadata }}
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{secrets.GCP_IDENTITY_PROVIDER}}
          service_account: ${{secrets.GCP_FUNCTION_ADMIN_SERVICE_ACCOUNT}}
      - uses: google-github-actions/setup-gcloud@v2
      - run: gcloud auth configure-docker us-central1-docker.pkg.dev
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Hash ${{github.sha}}
        run: echo "${{github.sha}}"
      - name: Build Copy Task
        uses: docker/build-push-action@v6
        id: build-action-get
        with:
          push: true
          tags: |
            us-central1-docker.pkg.dev/kotori316-mods-resources/reposilite-server-copy-job-registory/copy_task:${{github.sha}}
            us-central1-docker.pkg.dev/kotori316-mods-resources/reposilite-server-copy-job-registory/copy_task:latest
          platforms: linux/amd64
          context: 'reposilite-server-terraform/copy_job'
          file: 'reposilite-server-terraform/copy_job/Dockerfile'

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{secrets.GCP_IDENTITY_PROVIDER}}
          service_account: ${{secrets.GCP_FUNCTION_ADMIN_SERVICE_ACCOUNT}}
      - name: Check image name
        run: echo "IMAGE_NAME=$(echo "$METADATA" | jq -r '."image.name"')" >> $GITHUB_OUTPUT
        id: image
        env:
          METADATA: ${{ needs.build.outputs.metadata }}
      - name: Deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          job: 'reposilite-server-copy-job'
          region: 'us-central1'
          image: '${{ steps.image.outputs.IMAGE_NAME }}'
          skip_default_labels: true
