name: Deploy Pages
on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
        default: 'preview'
  schedule:
    - cron: "20 19 * * *" # 04:20 in JST
  workflow_dispatch:
    inputs:
      branch:
        required: true
        default: 'preview'
        description: 'Target environment'
        type: choice
        options:
          - preview
          - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      id-token: write
      contents: read
    environment:
      name: ${{ (inputs.branch || 'main') == 'main' && 'workers' || 'workers_preview' }}
      # url: ${{ (inputs.branch || 'main') == 'main' && 'https://maven.kotori316.com' || format('https://{0}.maven.kotori316.com', inputs.branch) }}
    concurrency:
      group: ${{ inputs.branch || 'main' }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
        working-directory: workers
      - run: npm ci
        working-directory: ssg
      - run: npm run css
        working-directory: workers
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{secrets.GCP_IDENTITY_PROVIDER}}
          service_account: ${{secrets.GCP_SERVICE_ACCOUNT}}
      - name: Get credentials
        id: get-secrets
        uses: google-github-actions/get-secretmanager-secrets@v2
        with:
          secrets: |-
            cloudflare_token:kotori316-mods-resources/cloudflare_token
            cloudflare_access_key:kotori316-mods-resources/cloudflare_access_key
            cloudflare_s3_endpoint:kotori316-mods-resources/cloudflare_s3_endpoint
            cloudflare_secret_key:kotori316-mods-resources/cloudflare_secret_key
      - name: Run SSG
        working-directory: ssg
        run: npm run build
        env:
          R2_ENDPOINT: ${{steps.get-secrets.outputs.cloudflare_s3_endpoint}}
          R2_ACCESS_KEY: ${{steps.get-secrets.outputs.cloudflare_access_key}}
          R2_SECRET_KEY: ${{steps.get-secrets.outputs.cloudflare_secret_key}}
          R2_BUCKET: 'kotori316-maven'
          DIRECTORY_PAGE_PREFIX: '/static/ssg'
      - name: Deploy
        id: action
        run: |
          log_name="$(date "+%Y%m%d-%H%M%S")-npm-deploy.log"
          echo "${{ github.actor }}" >> "/tmp/${log_name}"
          echo "branch=${{ inputs.branch || 'main' }}" >> "/tmp/${log_name}"
          echo "name=${log_name}" >> $GITHUB_OUTPUT
          echo "repo=$(basename "${{github.repository}}")" >> $GITHUB_OUTPUT
          npm run deploy >>"/tmp/${log_name}" 2>&1 && echo "Published successfully" || (echo "Failed to publish"; false)
        env:
          CLOUDFLARE_API_TOKEN: ${{steps.get-secrets.outputs.cloudflare_token}}
          NO_COLOR: true
          BRANCH: ${{ inputs.branch || 'main' }}
        working-directory: workers
      - name: Upload log
        if: ${{ !cancelled() }}
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: /tmp/${{steps.action.outputs.name}}
          destination: kotori316-logs/${{steps.action.outputs.repo}}
          process_gcloudignore: false
