name: Deploy Workers
on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: false
        default: 'preview'
  workflow_dispatch:
    inputs:
      branch:
        required: true
        default: 'preview'
        description: 'Target environment'
        type: choice
        options:
          - preview
          - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      id-token: write
      contents: read
    environment:
      name: ${{ (inputs.branch || 'main') == 'main' && 'workers' || 'workers_preview' }}
      # url: ${{ (inputs.branch || 'main') == 'main' && 'https://maven.kotori316.com' || format('https://{0}.maven.kotori316.com', inputs.branch) }}
    concurrency:
      group: ${{ inputs.branch || 'main' }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: 'workers/package.json'
      - run: npm ci
        working-directory: workers
      - uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          workload_identity_provider: ${{secrets.GCP_IDENTITY_PROVIDER}}
          service_account: ${{secrets.GCP_SERVICE_ACCOUNT}}
      - name: Get credentials
        id: get-secrets
        uses: google-github-actions/get-secretmanager-secrets@bc9c54b29fdffb8a47776820a7d26e77b379d262 # v3.0.0
        with:
          secrets: |-
            cloudflare_token:kotori316-mods-resources/cloudflare_token
      - name: Deploy
        id: action
        run: |
          log_name="$(date "+%Y%m%d-%H%M%S")-npm-deploy.log"
          echo "$GITHUB_ACTOR" >> "/tmp/${log_name}"
          echo "branch=$BRANCH" >> "/tmp/${log_name}"
          echo "name=${log_name}" >> "$GITHUB_OUTPUT"
          echo "repo=$(basename "$GITHUB_REPOSITORY")" >> "$GITHUB_OUTPUT"
          if npm run deploy >>"/tmp/${log_name}" 2>&1; then echo "Published successfully"; else echo "Failed to publish"; false; fi
        env:
          CLOUDFLARE_API_TOKEN: ${{steps.get-secrets.outputs.cloudflare_token}}
          NO_COLOR: true
          BRANCH: ${{ inputs.branch || 'main' }}
        working-directory: workers
      - name: Upload log
        if: ${{ !cancelled() }}
        uses: google-github-actions/upload-cloud-storage@6397bd7208e18d13ba2619ee21b9873edc94427a # v3.0.0
        with:
          path: /tmp/${{steps.action.outputs.name}}
          destination: kotori316-logs/${{steps.action.outputs.repo}}
          process_gcloudignore: false
